name: Deploy Sara Bot Website

on: 
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Website
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Top.gg API
        env:
          TOPGG_API: ${{ secrets.topgg_api }}
        run: |
          echo "Configurando token de Top.gg"
          echo "TOPGG_API=$TOPGG_API" >> $GITHUB_ENV

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          enable_jekyll: false